# nsenter 逃逸测试镜像（util-linux）
FROM ubuntu:22.04
RUN sed -i "s/archive.ubuntu.com/mirrors.aliyun.com/g" /etc/apt/sources.list && apt-get update -qq && apt-get install -y -qq --no-install-recommends \
    util-linux && rm -rf /var/lib/apt/lists/*
CMD ["sleep", "infinity"]
