# 挂载逃逸测试镜像（procfs/docker.sock 挂载）
FROM ubuntu:22.04
RUN sed -i "s/archive.ubuntu.com/mirrors.aliyun.com/g" /etc/apt/sources.list && apt-get update -qq && apt-get install -y -qq --no-install-recommends \
    util-linux mount && rm -rf /var/lib/apt/lists/*
CMD ["sleep", "infinity"]
